import Zeta23Ext.VerifiedAnnotatedForestDecoder

#print axioms Zeta23Ext.VerifiedCertificate.AnnotatedDecoder.decodeForest_length
#print axioms Zeta23Ext.VerifiedCertificate.AnnotatedDecoder.currentLocalCertificate_of_decoded_annotated_replay
