import Zeta23Ext.CurrentTangentCompactRangeEvidence

open Zeta23Ext.VerifiedCertificate.CurrentTangent.CompactRange

#print axioms Evidence.secondDerivative_sound_inBox
#print axioms Certificate.range_sound
