import Zeta23Ext.Current
import Zeta23Ext.CertificateBridge
import Zeta23Ext.CurrentZetaAssembly
import Zeta23Ext.CurrentSpan
import Zeta23Ext.CurrentAnalyticBridge
import Zeta23Ext.CurrentAnalyticInstantiation
import Zeta23Ext.CurrentWindowMoments
import Zeta23Ext.CurrentXiSpecialization
import Zeta23Ext.VerifiedCertificate
import Zeta23Ext.TranscendentalBounds
import Zeta23Ext.RationalTrigCell
import Zeta23Ext.CurrentKernelFormula
import Zeta23Ext.CurrentWindowAdmissibility
import Zeta23Ext.CurrentWindowFiniteCertificate
import Zeta23Ext.CurrentWindowUniformGrid
import Zeta23Ext.CurrentWindowClosedHScalable
import Zeta23Ext.VerifiedCertificateForest
import Zeta23Ext.VerifiedCertificateArithmetic
import Zeta23Ext.CurrentCertificateReplay
import Zeta23Ext.VerifiedCertificateRoots
import Zeta23Ext.CurrentInitialRoots
import Zeta23Ext.VerifiedAnnotatedForest
import Zeta23Ext.CurrentZetaNative
import Zeta23Ext.CurrentRetainedWithLoss
import Zeta23Ext.CurrentZetaAutocorr
import Zeta23Ext.CurrentZetaEndpoint
import Zeta23Ext.CurrentCentralSimple
import Zeta23Ext.CurrentCentralSelection
import Zeta23Ext.CurrentCentralAssembler
import Zeta23Ext.CurrentCompactGram
import Zeta23Ext.CurrentInfiniteKernel
import Zeta23Ext.CurrentInteriorRetention
import Zeta23Ext.CurrentInteriorRetentionBridge
import Zeta23Ext.CurrentInteriorAnalyticPackage
import Zeta23Ext.SincDerivativeCertificate
import Zeta23Ext.SincJetCertificate
import Zeta23Ext.CurrentKernelDerivatives
import Zeta23Ext.ProductionCell4376Jets

/-
Run with `lake env lean Zeta23Ext/PrintCurrentAxioms.lean` to audit the
Lean-checked current-result seams.  Remaining external inputs are propositions
in theorem arguments, not declared axioms.
-/

#print axioms Zeta23Ext.Weighted.paper_window_summation_250
#print axioms Zeta23Ext.SqrtProfile.block_defect_sqrt
#print axioms Zeta23Ext.ProfileSharpness.tendsto_actualDefect
#print axioms Zeta23Ext.CurrentBlockMatrix.paper_block_matrix
#print axioms Zeta23Ext.CurrentAveraging.current_averaged_defect_normalized
#print axioms Zeta23Ext.Current.target_lt_headline
#print axioms Zeta23Ext.Current.zeta_conditional_target
#print axioms Zeta23Ext.Current.zeta_conditional_target_cumulative
#print axioms Zeta23Ext.Current.zeta_conditional_target_cumulative_unconditional_rvm
#print axioms Zeta23Ext.CertificateBridge.mainReportAccepted
#print axioms Zeta23Ext.CertificateBridge.fastReportAccepted
#print axioms Zeta23Ext.CertificateBridge.finiteWindowInputs_of_externalSoundness
#print axioms Zeta23Ext.CurrentAssembly.FiniteHeightInputs.toWeightedBlockDefectData
#print axioms Zeta23Ext.CurrentAssembly.AsymptoticInputs.target
#print axioms Zeta23Ext.CurrentZetaAssembly.toCurrentZetaAnalyticInputs
#print axioms Zeta23Ext.CurrentZetaAssembly.zeta_target
#print axioms Zeta23Ext.CurrentZetaAssembly.zeta_target_cumulative
#print axioms Zeta23Ext.CurrentZetaAssembly.retained_ncard_le_N0simple
#print axioms Zeta23Ext.CurrentZetaAssembly.zeta_target_cumulative_of_retained
#print axioms Zeta23Ext.CurrentSpan.zeta_spanError_isLittleO_count
#print axioms Zeta23Ext.CurrentSpan.zeta_spanControl_of_normalized_endpoint_bounds
#print axioms Zeta23Ext.CurrentSpan.zeta_pressureSpanError_isLittleO_count
#print axioms Zeta23Ext.CurrentAnalyticBridge.currentWindowZeroSide
#print axioms Zeta23Ext.CurrentAnalyticBridge.PairwiseGramData.guardedBlockApprox
#print axioms Zeta23Ext.CurrentAnalyticBridge.MomentData.stabilitySeam
#print axioms Zeta23Ext.CurrentAnalyticBridge.AsymptoticAnalyticInputs.target
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.current_bv_half
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.current_c1_inv_le
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.current_admFamily_atV
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.current_gzMoments
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.current_gzMoments_c1
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.RetainedZeroData.ncard_le_N0simple
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.RetainedZeroData.colSq_V_le
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.RetainedZeroData.V_mul_add_Q
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.RetainedZeroData.toRetainedDecomposition
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.eventually_retainedMomentData
#print axioms Zeta23Ext.CurrentAnalyticInstantiation.eventually_entrywiseGramData_of_compactUniform
#print axioms Zeta23Ext.CurrentWindowMoments.current_window_sq_integral_pos
#print axioms Zeta23Ext.CurrentWindowMoments.tendsto_aV_current
#print axioms Zeta23Ext.CurrentWindowMoments.tendsto_bV_current
#print axioms Zeta23Ext.CurrentWindowMoments.tendsto_cRatio_current_of_autocorr
#print axioms Zeta23Ext.CurrentXiSpecialization.current_cWin_D1_pos
#print axioms Zeta23Ext.CurrentXiSpecialization.current_traceTransfer_xi
#print axioms Zeta23Ext.CurrentXiSpecialization.current_coeffMoments_xi
#print axioms Zeta23Ext.CurrentXiSpecialization.current_gzMoments_xiDeriv
#print axioms Zeta23Ext.CurrentXiSpecialization.current_gzMoments_xiDeriv_of_autocorr
#print axioms Zeta23Ext.VerifiedCertificate.Tree.check_sound
#print axioms Zeta23Ext.VerifiedCertificate.currentLocalCertificate_of_checked_tree
#print axioms Zeta23Ext.TranscendentalBounds.abs_sin_sub_sinTaylorWithin_le
#print axioms Zeta23Ext.TranscendentalBounds.sin_mem_taylor7_center_interval
#print axioms Zeta23Ext.TranscendentalBounds.sin_one_half_bounds
#print axioms Zeta23Ext.TranscendentalBounds.cos_mem_taylor8_interval
#print axioms Zeta23Ext.TranscendentalBounds.cos_one_half_bounds
#print axioms Zeta23Ext.TranscendentalBounds.sqrt_mem_interval
#print axioms Zeta23Ext.TranscendentalBounds.sqrt_two_bounds
#print axioms Zeta23Ext.TranscendentalBounds.pi_rational_bounds
#print axioms Zeta23Ext.TranscendentalBounds.abs_sinc_sub_sincTaylor6_le
#print axioms Zeta23Ext.RationalTrigCell.check_sound
#print axioms Zeta23Ext.RationalTrigCell.sin_sound
#print axioms Zeta23Ext.RationalTrigCell.cos_sound
#print axioms Zeta23Ext.RationalTrigCell.weighted_sum_le
#print axioms Zeta23Ext.CurrentKernelFormula.integral_cos_linear
#print axioms Zeta23Ext.CurrentKernelFormula.integral_cos_mul_cos
#print axioms Zeta23Ext.CurrentKernelFormula.kernel_eq_closedKernel
#print axioms Zeta23Ext.CurrentKernelFormula.closedKernel_zero_pos
#print axioms Zeta23Ext.CurrentKernelFormula.weight_eq_closedKernel
#print axioms Zeta23Ext.CurrentKernelFormula.dyadicTableSound_weight_iff
#print axioms Zeta23Ext.CurrentWindowAdmissibility.modFactor_current
#print axioms Zeta23Ext.CurrentWindowAdmissibility.admWindow_current
#print axioms Zeta23Ext.CurrentWindowAdmissibility.currentWindowAdmissibility
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.abs_deriv3_window_le
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.origin_second_upper
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.derivative_nonpos_of_table
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.windowSquareMass_closed
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.integral_abs_cos_cos
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.windowDistanceMass_closed
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.H_eq_closedH
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.H_lower_iff_closedHLower
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.cos_sqrt_two_half_lower
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.window_half_lower
#print axioms Zeta23Ext.CurrentWindowFiniteCertificate.NumericCertificate.toWindowCertificate
#print axioms Zeta23Ext.CurrentWindowUniformGrid.Certificate.toAwayMonotonicityTable
#print axioms Zeta23Ext.CurrentWindowUniformGrid.Certificate.window_antitone
#print axioms Zeta23Ext.CurrentWindowClosedHScalable.closed_masses_eq_entry_sum
#print axioms Zeta23Ext.CurrentWindowClosedHScalable.combinedEntry_zero_zero
#print axioms Zeta23Ext.CurrentWindowClosedHScalable.combinedEntry_one_one
#print axioms Zeta23Ext.CurrentWindowClosedHScalable.combinedEntry_one_two
#print axioms Zeta23Ext.CurrentWindowClosedHScalable.strong_closedH_lower_of_compact
#print axioms Zeta23Ext.VerifiedCertificate.Forest.check_sound
#print axioms Zeta23Ext.VerifiedCertificate.currentLocalCertificate_of_decoded_forest
#print axioms Zeta23Ext.VerifiedCertificate.TermwiseIntegerBounds.lowerScore_sound
#print axioms Zeta23Ext.VerifiedCertificate.gridCell_lower
#print axioms Zeta23Ext.VerifiedCertificate.CurrentReplay.RangeKernelTable.rangeLower_sound
#print axioms Zeta23Ext.VerifiedCertificate.CurrentReplay.lowerScore_sound
#print axioms Zeta23Ext.VerifiedCertificate.CurrentReplay.exactScore_div_scale_le
#print axioms Zeta23Ext.VerifiedCertificate.CurrentReplay.pressure_cutoff_local
#print axioms Zeta23Ext.VerifiedCertificate.CurrentReplay.currentLocalCertificate_of_replay
#print axioms Zeta23Ext.VerifiedCertificate.decodeRootBoxes_length
#print axioms Zeta23Ext.VerifiedCertificate.currentLocalCertificate_of_decoded_artifacts
#print axioms Zeta23Ext.VerifiedCertificate.CurrentInitialRoots.roots_length
#print axioms Zeta23Ext.VerifiedCertificate.CurrentInitialRoots.covers_roots
#print axioms Zeta23Ext.VerifiedCertificate.CurrentInitialRoots.decoded_roots_cover
#print axioms Zeta23Ext.VerifiedCertificate.CurrentInitialRoots.oneBodyScore_implies_local
#print axioms Zeta23Ext.VerifiedCertificate.CurrentInitialRoots.initialCheck_cell
#print axioms Zeta23Ext.VerifiedCertificate.CurrentInitialRoots.initial_classify
#print axioms Zeta23Ext.VerifiedCertificate.CurrentInitialRoots.currentLocalCertificate_of_decoded_replay
#print axioms Zeta23Ext.VerifiedCertificate.Annotated.Tree.check_sound
#print axioms Zeta23Ext.VerifiedCertificate.Annotated.Forest.checked_sound
#print axioms Zeta23Ext.VerifiedCertificate.Annotated.Demo.mixedTree_sound
#print axioms Zeta23Ext.CurrentZetaNative.GpC_zetaCoeffFamily_eq_Gp
#print axioms Zeta23Ext.CurrentZetaNative.zetaCoeffFamily_hyps
#print axioms Zeta23Ext.CurrentZetaNative.current_zeta_traceTransfer
#print axioms Zeta23Ext.CurrentZetaNative.current_zeta_gzMoments_of_coeffMoments
#print axioms Zeta23Ext.CurrentZetaNative.current_zeta_gzMoments_of_autocorr
#print axioms Zeta23Ext.CurrentRetainedWithLoss.PrincipalCompression.remainder_posIndex_le
#print axioms Zeta23Ext.CurrentRetainedWithLoss.count_seam_of_deleted
#print axioms Zeta23Ext.CurrentRetainedWithLoss.LossyMomentData.stabilitySeam
#print axioms Zeta23Ext.CurrentRetainedWithLoss.LossyAsymptoticEntrywiseInputs.ofLittleO
#print axioms Zeta23Ext.CurrentRetainedWithLoss.LossyAsymptoticEntrywiseInputs.target
#print axioms Zeta23Ext.CurrentRetainedWithLoss.target_of_littleO
#print axioms Zeta23Ext.CurrentZetaAutocorr.currentAutocorr
#print axioms Zeta23Ext.CurrentZetaAutocorr.current_zeta_gzMoments
#print axioms Zeta23Ext.CurrentZetaEndpoint.current_cWin_one_eq_c1
#print axioms Zeta23Ext.CurrentZetaEndpoint.exists_current_zeta_moment_params_of_Hcert_lt
#print axioms Zeta23Ext.CurrentCentralSimple.AllSimple.allSimple_decomposition
#print axioms Zeta23Ext.CurrentCentralSimple.concreteAllSimpleQ_posIndex_le
#print axioms Zeta23Ext.CurrentCentralSimple.ConcreteCentralSelection.lossyRetained
#print axioms Zeta23Ext.CurrentCentralSimple.CentralAzMomentPremise.ofGzTail
#print axioms Zeta23Ext.CurrentCompactGram.gramEntry_eq_Kfun_div
#print axioms Zeta23Ext.CurrentCompactGram.norm_gramEntry_sub_normalizedInfiniteKernel_le
#print axioms Zeta23Ext.CurrentCompactGram.eventually_currentLocalHypsCore
#print axioms Zeta23Ext.SincDerivativeCertificate.hasDerivAt_sinc
#print axioms Zeta23Ext.SincDerivativeCertificate.hasDerivAt_sincD1
#print axioms Zeta23Ext.SincDerivativeCertificate.SecondWitness.lower_sound
#print axioms Zeta23Ext.SincJetCertificate.Witness.sound
#print axioms Zeta23Ext.SincJetCertificate.productionReducedWitness_checked
#print axioms Zeta23Ext.SincJetCertificate.productionReducedWitness_sound
#print axioms Zeta23Ext.CurrentKernelDerivatives.closedWeightD2_lower_of_sign_bounds
#print axioms Zeta23Ext.CurrentKernelDerivatives.cell4376_scalar_check
#print axioms Zeta23Ext.CurrentKernelDerivatives.cell4376_arguments_nonzero
#print axioms Zeta23Ext.CurrentKernelDerivatives.sinc_sqrt_two_half_bounds
#print axioms Zeta23Ext.ProductionCell4376Jets.plusOne_checked
#print axioms Zeta23Ext.ProductionCell4376Jets.plusOne_sound
#print axioms Zeta23Ext.ProductionCell4376Jets.plusTwo_checked
#print axioms Zeta23Ext.ProductionCell4376Jets.plusTwo_sound
#print axioms Zeta23Ext.CurrentInfiniteKernel.uniformly_normalizedInfiniteKernel_current
#print axioms Zeta23Ext.CurrentInfiniteKernel.Wfun_le_four
#print axioms Zeta23Ext.CurrentInfiniteKernel.compactUniformScaledCurrentGram_of_rhoTail
#print axioms Zeta23Ext.CurrentInteriorRetention.endpointDeletion_isLittleO_N
#print axioms Zeta23Ext.CurrentInteriorRetention.eventually_current_interior_rho_tail
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.currentEndpointDeletion_isLittleO_NIprime
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.orderedCanonicalInteriorCompression_V_eq_retainedV
#print axioms Zeta23Ext.CurrentInteriorAnalyticPackage.tendsto_currentInteriorGramError
#print axioms Zeta23Ext.CurrentInteriorAnalyticPackage.eventually_currentInterior_entrywiseGramData
#print axioms Zeta23Ext.CurrentInteriorAnalyticPackage.InteriorHeightPremises.toLossyFinite
#print axioms Zeta23Ext.CurrentCentralSelection.canonicalRetainedZeroData
#print axioms Zeta23Ext.CurrentCentralSelection.canonical_lossyMomentData
#print axioms Zeta23Ext.CurrentCentralAssembler.CanonicalHeightPremises.toLossyFinite
#print axioms Zeta23Ext.CurrentCentralAssembler.target_of_boundaryLossLittleO
