import Zeta23Ext.CurrentInteriorRetention
import Zeta23Ext.CurrentInteriorRetentionBridge

#print axioms Zeta23Ext.CurrentInteriorRetention.canonicalInteriorCompression
#print axioms Zeta23Ext.CurrentInteriorRetention.card_endpointIndex_le_counts
#print axioms Zeta23Ext.CurrentInteriorRetention.endpointDeletion_isLittleO_N
#print axioms Zeta23Ext.CurrentInteriorRetention.normalized_rho_le_rhoMarginError
#print axioms Zeta23Ext.CurrentInteriorRetention.tendsto_rhoMarginError_marginScale
#print axioms Zeta23Ext.CurrentInteriorRetention.interiorIndex_normalized_rho_le
#print axioms Zeta23Ext.CurrentInteriorRetention.eventually_current_interior_rho_tail
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.endpointDeletionFamily_isLittleO_N
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.currentEndpointDeletion_isLittleO_N
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.currentEndpointDeletion_isLittleO_NIprime
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.orderedInteriorEndpointEquiv_inl
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.orderedCanonicalInteriorCompression_V_eq_retainedV
#print axioms Zeta23Ext.CurrentInteriorRetentionBridge.eventually_nonempty_interiorRetainedZeroData
